import * as M from './model.js';
import {read,transact,subscribe,restoreRecovery} from './storage.js';
import {backupFilename,META_KEY} from './backup.js';
import {guideContent,createTour} from './help.js';
const $=(q,root=document)=>root.querySelector(q),$$=(q,root=document)=>[...root.querySelectorAll(q)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tour, backupMeta={};
let state, route='projects', selected=null, query='', showCompleted=true, reportRange='all', dragged=null, toastTimeout, modalContext=null;
const drafts=new Map(), main=$('#main'), modal=$('#modal');
const dateLabel=d=>d?new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Not set';
const atLabel=ms=>new Date(ms).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const pct=p=>p===null?'—':p+'%';
const countTasks=()=>state.projects.flatMap(p=>p.tasks);
const status=p=>p.progress===100?['Complete','active']:p.end&&p.end<M.today()?['Overdue','late']:p.progress>0?['In progress','active']:['Not started',''];
const badge=p=>{const [text,cls]=status(p);return `<span class="badge ${cls}">${text}</span>`;};
const bar=(value,color)=>`<div class="track" role="progressbar" aria-valuemin="0" aria-valuemax="100" ${value!==null?`aria-valuenow="${value}"`:''} aria-label="${value===null?'Progress not set':`${value}% complete`}" style="--color:${color||'var(--green)'}"><span style="width:${value||0}%"></span></div>`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
async function change(fn,opts){try{state=await transact(fn,opts);render();return true;}catch(e){render();toast('Could not save: '+e.message);return false;}}
function nav(to,pid=null){route=to;selected=pid;query='';location.hash=pid?'project/'+encodeURIComponent(pid):to;render();window.scrollTo(0,0);}
function parseHash(){const [r,id]=location.hash.slice(1).split('/');route=['projects','project','reports','backup','credits','appearance','guide'].includes(r)?r:'projects';selected=id?decodeURIComponent(id):null;}
function render(){document.body.dataset.theme=state.settings.theme;document.body.dataset.design=state.settings.design||'modern';$('#theme-toggle').textContent=state.settings.theme==='dark'?'☀  Use light mode':'◐  Use dark mode';$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===route||(route==='project'&&b.dataset.nav==='projects')));$('#project-count').textContent=state.projects.length;
 if(route==='project'&&!state.projects.some(p=>p.id===selected)){route='projects';selected=null;}
 main.innerHTML=route==='project'?detail():route==='reports'?reports():route==='backup'?backup():route==='credits'?credits():route==='appearance'?appearance():route==='guide'?guide():projects();renderTimer();tour?.highlight();}
function header(title,subtitle,actions='',eyebrow='A LITTLE CLARITY. A LITTLE MOMENTUM.'){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div><div class="actions no-print">${actions}</div></div>`;}
function stat(label,value,foot,icon){return `<div class="stat"><span class="stat-icon" aria-hidden="true">${icon}</span><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></div>`;}
function projects(){const ps=state.projects,tasks=countTasks(),done=ps.filter(p=>p.progress===100).length;
 return header('Your projects, in perspective.','Make room for the things you want to move forward.','<button class="primary" data-action="new-project">＋ New project</button>')+
 `<div class="stats">${stat('Total projects',ps.length,'A place for every idea','▦')}${stat('In progress',ps.filter(p=>p.progress>0&&p.progress<100).length,'Good things are taking shape','◔')}${stat('Completed',done,`${tasks.filter(t=>t.completed).length} of ${tasks.length} tasks checked off`,'✓')}${stat('Time invested',M.timeText(ps.reduce((n,p)=>n+M.duration(M.sessionsFor(p,state)),0)),'Every bit of effort counts','◷')}</div>
 <div class="toolbar"><h2>All projects <span class="muted small-text"> / ${ps.length}</span></h2><input id="search" aria-label="Search projects" placeholder="Search projects…" value="${esc(query)}"><select id="sort" aria-label="Sort projects">${[['manual','Custom order'],['name:asc','Name · A → Z'],['name:desc','Name · Z → A'],['start:asc','Start date · earliest'],['start:desc','Start date · latest'],['end:asc','End date · earliest'],['end:desc','End date · latest']].map(([v,l])=>`<option value="${v}" ${state.settings.sort===v?'selected':''}>${l}</option>`).join('')}</select></div>
 <div id="project-results">${projectResults()}</div>`;
}
function projectResults(){const ps=M.sorted(state.projects,state.settings.sort).filter(p=>(p.name+' '+p.description).toLowerCase().includes(query.toLowerCase()));return ps.length?`<div class="project-grid">${ps.map(card).join('')}</div><p class="hint">${state.settings.sort==='manual'?'Drag the ⋮⋮ handle to arrange your projects. Arrow buttons work too.':'Choose Custom order to arrange projects by drag and drop.'} · Dates are optional. Progress is yours to set.</p>`:`<div class="empty"><div class="empty-art" aria-hidden="true">◎</div><h2>${query?'No matching projects.':'Big ideas. Small beginnings.'}</h2><p>${query?'Try another name or description.':'A name is all you need. Give your next idea a little space to grow.'}</p>${query?'':'<button class="primary" data-action="new-project">＋ Create your first project</button>'}</div>`;}
function reorderControls(id,kind){return `<div class="move-controls"><button data-action="move" data-kind="${kind}" data-id="${esc(id)}" data-dir="-1" aria-label="Move earlier" title="Move earlier">↑</button><button data-action="move" data-kind="${kind}" data-id="${esc(id)}" data-dir="1" aria-label="Move later" title="Move later">↓</button><button class="drag-handle" draggable="true" data-kind="${kind}" data-id="${esc(id)}" aria-label="Drag to reorder" title="Drag to reorder">⋮⋮</button></div>`;}
function card(p){const done=p.tasks.filter(t=>t.completed).length;return `<article class="project-card" data-project="${esc(p.id)}" data-drop="project" data-id="${esc(p.id)}" style="--color:${p.color}"><div class="card-top"><span class="project-symbol" aria-hidden="true">${esc(p.name[0].toUpperCase())}</span>${badge(p)}</div><button class="card-name" data-action="open-project" data-id="${esc(p.id)}">${esc(p.name)}</button><p class="card-desc">${esc(p.description||'A little space for your next step.')}</p><div class="progress-caption"><span>Progress</span><strong>${pct(p.progress)}</strong></div>${bar(p.progress,p.color)}<div class="card-foot"><span>☑ &nbsp;${done}/${p.tasks.length} tasks</span><span>◷ &nbsp;${M.timeText(M.duration(M.sessionsFor(p,state)))}</span></div><div class="card-date"><span>${p.end?'Due '+dateLabel(p.end):'No deadline'}</span>${state.settings.sort==='manual'?reorderControls(p.id,'project'):''}</div></article>`;}
function progressControl(e,pid,tid=null){return `<div class="progress-big">${pct(e.progress)}</div><input type="range" min="0" max="100" value="${e.progress||0}" data-progress="${esc(pid)}" ${tid?`data-task="${esc(tid)}"`:''} aria-label="${tid?'Task':'Project'} progress"><div class="progress-actions"><span class="small-text muted">0%</span><span class="small-text muted" style="margin-left:auto">100%</span><button data-action="unset-progress" data-pid="${esc(pid)}" ${tid?`data-tid="${esc(tid)}"`:''}>Clear progress</button></div>`;}
function dates(e){return `<div class="date-pair"><div><span>START DATE</span><strong>${dateLabel(e.start)}</strong></div><div><span>END DATE</span><strong>${dateLabel(e.end)}</strong></div></div>`;}
function detail(){const p=M.locate(state,selected);return `<button class="back" data-nav="projects">← All projects</button>`+header(esc(p.name),esc(p.description||'One step at a time.'),`<button data-action="edit-project">Edit project</button><button class="primary" data-action="timer" data-pid="${esc(p.id)}">${timerActive(p.id)?'■ Stop timer':'▷ Start timer'}</button>`,'YOUR PROJECT')+
 `<div class="detail-layout"><div><section class="panel"><div class="panel-head"><h2>Checklist <span class="muted small-text">${p.tasks.filter(t=>t.completed).length} / ${p.tasks.length}</span></h2><label class="completion-switch"><input id="show-completed" type="checkbox" ${showCompleted?'checked':''}> Show completed</label></div><form id="add-task" class="add-task"><input name="name" aria-label="New task name" placeholder="What’s the next small step?" value="${esc(drafts.get('task:'+p.id)||'')}" required><button class="primary" type="submit">＋ Add</button></form><div class="task-list">${p.tasks.filter(t=>showCompleted||!t.completed).map(t=>taskRow(t)).join('')||'<p class="small-text muted">No tasks here yet. Add one above.</p>'}</div><p class="hint">Click a task for details, dates, notes and its own timer.</p></section>${notes(p,p.id)}</div><div><section class="panel"><div class="panel-head"><h2>Project progress</h2>${badge(p)}</div>${progressControl(p,p.id)}<p class="hint">Set overall progress independently of the checklist.</p>${dates(p)}${sparkline(p)}</section>${timePanel(p,p.id)}<button class="quiet danger small" data-action="delete-project">Delete project</button></div></div>`;}
function taskRow(t){return `<div class="task-row ${t.completed?'completed':''}" data-drop="task" data-id="${esc(t.id)}"><input type="checkbox" aria-label="Complete ${esc(t.name)}" data-check="${esc(t.id)}" ${t.completed?'checked':''}><button class="task-title" data-action="open-task" data-id="${esc(t.id)}">${esc(t.name)}${t.end?`<span class="task-meta">Due ${dateLabel(t.end)}</span>`:''}</button><span class="task-progress">${pct(t.progress)}</span>${reorderControls(t.id,'task')}</div>`;}
function notes(e,pid,tid=null){const key='note:'+(tid||pid);return `<section class="panel"><div class="panel-head"><h2>Notes & updates</h2><span class="small-text muted">${e.notes.length}</span></div><form class="note-form" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}"><textarea name="text" aria-label="New note" placeholder="An update, a thought, a small win…" required>${esc(drafts.get(key)||'')}</textarea><button class="primary small" type="submit">Add note</button></form>${[...e.notes].reverse().map(n=>`<article class="note"><div class="note-top"><time>${atLabel(n.at)}</time><span><button data-action="edit-note" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}" data-id="${esc(n.id)}">Edit</button><button data-action="delete-note" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}" data-id="${esc(n.id)}">Delete</button></span></div><p>${esc(n.text)}</p></article>`).join('')}</section>`;}
function timerActive(pid,tid=null){return state.timer?.projectId===pid&&state.timer?.taskId===tid;}
function timePanel(e,pid,tid=null){const total=tid?M.entityTime(e,state,pid,tid):M.duration(M.sessionsFor(e,state));return `<section class="panel"><div class="panel-head"><h2>Time invested</h2><span class="muted">◷</span></div><div class="time-total">${M.timeText(total)}</div><div class="actions"><button class="small" data-action="log-time" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}">＋ Log time</button><button class="small" data-action="timer" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}">${timerActive(pid,tid)?'■ Stop timer':'▷ Start timer'}</button></div><p class="hint">${tid?'Time on this task.':'Includes this project and all its tasks.'} Timers run until stopped, even if Chrome closes.</p><div class="time-list">${[...e.sessions].reverse().map(s=>`<div class="time-row"><div>${M.timeText(s.end-s.start)} · ${atLabel(s.start)}<small>${esc(s.note|| (s.kind==='timer'?'Timer session':'Manual time'))}</small></div><button data-action="edit-time" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}" data-id="${esc(s.id)}">Edit</button></div>`).join('')}</div></section>`;}
function sparkline(e){const points=e.history.filter(h=>h.progress!==null);if(points.length<2)return '';const start=points[0].at,end=points.at(-1).at;const coords=points.map((h,i)=>`${end===start?i/(points.length-1)*300:(h.at-start)/(end-start)*300},${55-h.progress*.5}`).join(' ');return `<svg class="sparkline" viewBox="0 0 300 60" preserveAspectRatio="none" role="img" aria-label="Progress history from ${points[0].progress}% to ${points.at(-1).progress}%"><polyline fill="none" stroke="currentColor" stroke-width="2" points="${coords}"/></svg><div class="small-text muted">Progress history · ${points.length} updates</div>`;}
function reports(){let from=-Infinity;const now=Date.now();if(reportRange!=='all'){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(Number(reportRange)-1));from=d.getTime();}const ps=state.projects;const times=ps.map(p=>({p,ms:M.duration(M.sessionsFor(p,state,now),from,now)}));const total=times.reduce((n,x)=>n+x.ms,0),known=ps.filter(p=>p.progress!==null),avg=known.length?Math.round(known.reduce((n,p)=>n+p.progress,0)/known.length):null,tasks=countTasks();let cursor=0;const gradient=times.filter(x=>x.ms).map(x=>{const start=cursor;cursor+=x.ms/total*100;return `${x.p.color} ${start}% ${cursor}%`;}).join(',');
 let days=[];for(let i=13;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const end=new Date(d);end.setDate(end.getDate()+1);const ms=ps.reduce((n,p)=>n+M.duration(M.sessionsFor(p,state,now),Math.max(from,d.getTime()),Math.min(now,end.getTime())),0);days.push({label:d.toLocaleDateString(undefined,{day:'numeric',month:'short'}),ms});}const max=Math.max(...days.map(d=>d.ms),1);
 return header('A clearer picture.','See what’s moving forward, and where your time goes.',`<select id="report-range" aria-label="Report time range">${[['all','All time'],['7','Last 7 days'],['30','Last 30 days'],['90','Last 90 days']].map(([v,l])=>`<option value="${v}" ${v===reportRange?'selected':''}>${l}</option>`).join('')}</select><button data-action="print">↗ Print / Save PDF</button>`,'YOUR PROGRESS, AT A GLANCE')+
 `<p class="print-heading">Locus · ${new Date().toLocaleString()} · Time range: ${reportRange==='all'?'All time':`Last ${reportRange} days`}</p><div class="stats">${stat('Average progress',pct(avg),`${known.length} projects with progress set`,'◔')}${stat('Completed projects',ps.filter(p=>p.progress===100).length,`Out of ${ps.length} projects`,'✓')}${stat('Tasks completed',`${tasks.filter(t=>t.completed).length}<span style="font-size:16px"> / ${tasks.length}</span>`,'Current checklist completion','☑')}${stat('Time invested',M.timeText(total),reportRange==='all'?'All recorded time':`In the last ${reportRange} days`,'◷')}</div>
 <div class="reports-grid"><section class="panel"><div class="panel-head"><h2>Project momentum</h2><span class="small-text muted">Current progress</span></div><div class="report-bars">${ps.map(p=>`<div><div class="bar-label"><span>${esc(p.name)}</span><strong>${pct(p.progress)}</strong></div>${bar(p.progress,p.color)}<div class="report-sub"><span>${p.tasks.filter(t=>t.completed).length}/${p.tasks.length} tasks complete</span><span>${status(p)[0]}</span></div></div>`).join('')||'<p class="small-text">Create a project to see its progress here.</p>'}</div></section>
 <section class="panel"><div class="panel-head"><h2>Where your time goes</h2></div><div class="donut-layout"><div class="donut-wrap"><div class="donut" ${gradient?`style="background:conic-gradient(${gradient})"`:''} role="img" aria-label="Recorded time by project; breakdown follows"></div><div class="donut-center"><strong>${M.timeText(total)}</strong><small>TOTAL INVESTED</small></div></div><div class="legend">${times.filter(x=>x.ms).map(x=>`<div class="legend-row"><span class="dot" style="background:${x.p.color}"></span><span>${esc(x.p.name)}</span><strong>${Math.round(x.ms/total*100)}%</strong></div>`).join('')||'<p class="small-text">Start a timer or log time to see the breakdown.</p>'}</div></div><p class="hint">Project time includes its tasks. Each entry is counted once.</p></section>
 <section class="panel report-span"><div class="panel-head"><h2>A little effort, every day</h2><span class="small-text muted">Last 14 days · hours logged</span></div><div class="activity-chart">${days.map(d=>`<div class="activity-day" title="${d.label}: ${M.timeText(d.ms)}"><span>${d.ms?(d.ms/3600000).toFixed(1):'—'}</span><div class="activity-bar" style="height:${Math.max(2,d.ms/max*115)}px"></div><span>${d.label}</span></div>`).join('')}</div><p class="hint">Time filter applies to logged effort. Progress and checklist totals show their current state.</p></section>
 <section class="panel report-span"><div class="panel-head"><h2>The details</h2><span class="small-text muted">Project & task breakdown</span></div><div class="table-scroll"><table class="report-table"><thead><tr><th>Project / task</th><th>Progress</th><th>Start</th><th>End</th><th>Logged time</th></tr></thead><tbody>${times.map(({p,ms})=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${pct(p.progress)}</td><td>${dateLabel(p.start)}</td><td>${dateLabel(p.end)}</td><td><strong>${M.timeText(ms)}</strong></td></tr>${p.tasks.map(t=>{const ss=[...t.sessions];if(timerActive(p.id,t.id))ss.push({start:state.timer.startedAt,end:now});return `<tr><td>↳ ${esc(t.name)}</td><td>${pct(t.progress)}</td><td>${dateLabel(t.start)}</td><td>${dateLabel(t.end)}</td><td>${M.timeText(M.duration(ss,from,now))}</td></tr>`;}).join('')}`).join('')}</tbody></table></div></section></div>`;}
function backup(){return header('Your work. Yours to keep.','Take everything with you, or pick up where you left off.','','BACKUP & RESTORE')+`<div class="settings-wrap">${automaticBackups()}<section class="panel"><h2>Export your workspace</h2><p>Download every project, task, note, progress update and time entry as a JSON file. A running timer is included up to the moment of export; the exported copy is paused.</p><div class="backup-actions"><button class="primary" data-action="export">↓ Export JSON</button><button data-action="offload">Export & clear workspace</button></div></section><section class="panel"><h2>Restore from a backup</h2><p>Import a Locus JSON file to replace this workspace. You’ll see a summary before anything changes. Your current workspace is kept as a recovery snapshot.</p><button data-action="import">↑ Choose JSON file</button></section><section class="panel"><h2>Recover the previous workspace</h2><p>Undo the most recent import, clear, or project/task deletion. Recovery swaps the current and previous workspaces. Running timers in the recovered copy are paused.</p><button data-action="recover">Restore recovery snapshot</button></section><p class="small-text muted">Data is stored only in this Chrome profile. No sign-in, syncing, analytics or remote services. Export a backup before uninstalling Locus or deleting this browser profile. Projects and notes have no app-imposed count limit; available disk space still applies.</p></div>`;}

function appearance(){return header('Make yourself at home.','Choose a design, then the light that suits you.','','APPEARANCE')+`<div class="theme-options">${[['modern','Modern','Rounded cards, airy spacing and a violet accent.'],['classic','Classic','Warm paper, traditional headings and structured borders.'],['minimalist','Minimalist','Grayscale, clean edges and fewer decorative details.']].map(([id,name,desc])=>`<button class="theme-option" data-action="set-design" data-design="${id}" aria-pressed="${(state.settings.design||'modern')===id}"><span class="theme-preview ${id}" aria-hidden="true"><span><i></i><i></i><i></i><i></i></span></span><strong>${name}</strong><small>${desc}</small></button>`).join('')}</div><section class="panel"><div class="panel-head"><h2>Light or dark</h2><span class="small-text muted">Works with every theme</span></div><div class="mode-group">${[['light','☀ Light'],['dark','◐ Dark']].map(([id,label])=>`<button data-action="set-mode" data-mode="${id}" aria-pressed="${state.settings.theme===id}">${label}</button>`).join('')}</div><p class="hint">Your choices are saved automatically and included in JSON backups.</p></section>`;}
function automaticBackups(){const freq=state.settings.backupFrequency||'daily';return `<section class="panel" id="automatic-backup-panel"><div class="panel-head"><h2>Automatic JSON backups</h2><span class="badge ${freq==='off'?'':'active'}">${freq==='off'?'Off':'Enabled'}</span></div><p>A complete copy, on your schedule. Files are saved to Chrome’s Downloads folder under <strong>Locus/Backups/YYYY-MM</strong>.</p><div class="actions"><label>Backup frequency<select id="backup-frequency">${[['hourly','Every hour'],['daily','Every day'],['weekly','Every week'],['off','Off']].map(([v,label])=>`<option value="${v}" ${freq===v?'selected':''}>${label}</option>`).join('')}</select></label><button data-action="backup-now">↓ Back up now</button></div><div class="backup-status"><dl><dt>Last success</dt><dd>${backupMeta.lastSuccess?atLabel(backupMeta.lastSuccess.at):'No completed backup yet'}</dd><dt>Next run</dt><dd>${freq==='off'?'Disabled':backupMeta.nextAt?atLabel(backupMeta.nextAt):'Scheduling…'}</dd><dt>Status</dt><dd>${backupMeta.pending?'Downloading…':backupMeta.error?'Needs attention':'Ready'}</dd>${backupMeta.lastSuccess?`<dt>Last file</dt><dd>${esc(backupMeta.lastSuccess.filename)}</dd>`:''}</dl>${backupMeta.error?`<p class="error" role="alert">${esc(backupMeta.error)}</p>`:''}</div><div class="filename-example">${backupFilename(state,'auto')}</div><p class="hint">UTC filenames prevent time-zone confusion. Chrome must be running; missed runs catch up when it resumes. Existing backups are kept. Chrome’s download settings may still prompt for a location.</p></section>`;}
function guide(){return header('A little guidance. A lot of possibility.','Everything you need to find your rhythm in Locus.','<button class="primary" data-action="start-tour">▷ Start guided tour</button><button data-action="print">Print guide</button>','USER GUIDE')+`<div class="guide-top"><p class="small-text">The seven-step tour includes safe practice controls. It never adds sample projects to your workspace.</p></div><div class="guide-grid">${guideContent()}</div>`;}

function credits(){return `<div class="credits"><img src="icons/128.png" alt="Locus"><h1>Your projects.<br>Your own pace.</h1><p>A quiet place for ideas, small steps and meaningful progress.<br>Private by design. Right here in your browser.</p><div class="credits-attribution"><strong>Imagined by Mohammed Kabir</strong><p>Developed by his agents.</p></div><div class="credits-links"><a href="https://www.evoknow.com" target="_blank" rel="noopener noreferrer">EVOKNOW</a><a href="https://x.com/mjkabir" target="_blank" rel="noopener noreferrer">Kabir on X</a><a href="https://github.com/evoknow-ai/locus" target="_blank" rel="noopener noreferrer">GitHub</a><button data-action="changelog">Changelog</button></div><small>Version 1.1.0 · <a href="LICENSE.txt" target="_blank" style="color:inherit">MIT License</a></small></div>`;}
function renderTimer(){const dock=$('#timer-dock');if(!state?.timer){dock.hidden=true;return;}const t=state.timer,p=state.projects.find(p=>p.id===t.projectId);if(!p){dock.hidden=true;return;}const target=t.taskId?p.tasks.find(x=>x.id===t.taskId):p;dock.hidden=false;dock.innerHTML=`<div><small>FOCUS TIMER</small><div class="timer-name">${esc(target?.name||p.name)}</div></div><strong>${M.timeText(Date.now()-t.startedAt,true)}</strong><button data-action="stop-timer">■ Stop</button>`;}
function showModal(html,context=null){modalContext=context;$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();modalContext=null;}
function modalHead(title){return `<div class="modal-head"><h2>${title}</h2><button data-action="close-modal" aria-label="Close dialog">×</button></div>`;}
function entityForm(kind,e=null){const editing=!!e, isTask=kind==='task';e=e|| (isTask?M.task(''):M.project(''));showModal(modalHead(`${editing?'Edit':'New'} ${kind}`)+`<form id="entity-form" data-kind="${kind}" data-id="${editing?esc(e.id):''}" class="form-grid"><label class="full">${isTask?'Task':'Project'} name<input name="name" value="${esc(e.name)}" placeholder="${isTask?'A small next step':'Something worth making happen'}" required autofocus></label><label class="full">Short description<textarea name="description" rows="2" placeholder="What’s this about?">${esc(e.description)}</textarea></label><label>Start date <span class="muted">Optional</span><input name="start" type="date" value="${e.start}"></label><label>End date <span class="muted">Optional</span><input name="end" type="date" value="${e.end}"></label><label class="full">Progress<div class="field-inline"><input name="progress" type="range" min="0" max="100" value="${e.progress||0}" aria-label="Progress"><output>${pct(e.progress)}</output><label><input type="checkbox" name="unset" ${e.progress===null?'checked':''}> Not set</label></div></label>${isTask?'':`<div class="full"><label>Project color</label><div class="color-picker" style="margin-top:12px">${M.COLORS.map((c,i)=>`<label style="--color:${c}"><input name="color" type="radio" value="${c}" aria-label="${['Forest','Terracotta','Slate blue','Plum','Gold','Ocean'][i]}" ${e.color===c?'checked':''}></label>`).join('')}</div></div>`}<p id="form-error" class="error full" role="alert"></p><div class="form-buttons full"><button type="button" data-action="close-modal">Cancel</button><button class="primary" type="submit">${editing?'Save changes':`Create ${kind}`}</button></div></form>`,{kind:'entity',revision:state.revision,returnTask:isTask&&editing?e.id:null});}
function openTask(id){const t=M.locate(state,selected,id);showModal(`<div class="task-modal">${modalHead(esc(t.name))}<p class="description small-text">${esc(t.description||'A small step forward.')}</p><div class="task-modal-actions"><button class="small" data-action="edit-task" data-id="${esc(id)}">Edit task</button><button class="small" data-action="toggle-task" data-id="${esc(id)}">${t.completed?'↶ Mark incomplete':'✓ Mark complete'}</button><button class="small danger" data-action="delete-task" data-id="${esc(id)}">Delete</button></div><section class="panel"><h3>Task progress</h3>${progressControl(t,selected,id)}${dates(t)}</section>${timePanel(t,selected,id)}${notes(t,selected,id)}</div>`,{kind:'task',id});}
function refreshTask(){if(modal.open&&modalContext?.kind==='task'){if(state.projects.find(p=>p.id===selected)?.tasks.some(t=>t.id===modalContext.id))openTask(modalContext.id);else closeModal();}}
function confirmModal(title,description,action){showModal(modalHead(esc(title))+`<p>${description}</p><div class="form-buttons"><button data-action="close-modal">Cancel</button><button class="primary" id="confirm-action">Continue</button></div>`);$('#confirm-action').onclick=async()=>{const b=$('#confirm-action');b.disabled=true;try{await action();}catch(e){toast(e.message);b.disabled=false;}};}
function logTime(pid,tid=null,id=null){const e=M.locate(state,pid,tid),entry=e.sessions.find(x=>x.id===id);const dt=entry?new Date(entry.start):new Date(Date.now()-30*60000);dt.setMinutes(dt.getMinutes()-dt.getTimezoneOffset());showModal(modalHead(entry?'Edit time entry':'Log time')+`<form id="time-form" class="form-grid" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}" data-id="${esc(id||'')}"><label class="full">Started at<input type="datetime-local" name="start" value="${dt.toISOString().slice(0,16)}" required></label><label>Hours<input name="hours" type="number" min="0" step="1" value="${entry?Math.floor((entry.end-entry.start)/3600000):0}" required></label><label>Minutes<input name="minutes" type="number" min="0" max="59.99" step="any" value="${entry?Number(((entry.end-entry.start)%3600000/60000).toFixed(2)):30}" required></label><label class="full">Note<textarea name="note" rows="2">${esc(entry?.note||'')}</textarea></label><p id="form-error" class="error full" role="alert"></p><div class="form-buttons full">${entry?'<button type="button" class="danger" id="delete-time">Delete entry</button>':''}<button type="button" data-action="close-modal">Cancel</button><button class="primary" type="submit">Save time</button></div></form>`,{kind:'time',pid,tid});if(entry)$('#delete-time').onclick=()=>confirmModal('Delete this time entry?','This entry will be removed from reports.',async()=>{if(await change(s=>{const x=M.locate(s,pid,tid);x.sessions=x.sessions.filter(t=>t.id!==id);},{backup:true})){closeModal();if(tid)openTask(tid);}});}
function download(){const blob=new Blob([JSON.stringify(M.snapshot(state),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=backupFilename(state,'manual');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}

// All imported and user-authored strings are escaped before insertion; no remote code or HTML notes.
document.addEventListener('click',async ev=>{const b=ev.target.closest('button, a[data-nav]');if(!b){const card=ev.target.closest('[data-project]');if(card&&!ev.target.closest('input,select,textarea,a'))nav('project',card.dataset.project);return;}if(b.dataset.nav){nav(b.dataset.nav);return;}const a=b.dataset.action,id=b.dataset.id,pid=b.dataset.pid,tid=b.dataset.tid||null;
 if(a==='start-tour'){closeModal();tour.start(route);return;}
 if(a==='set-design')await change(s=>{s.settings.design=b.dataset.design;});
 if(a==='set-mode')await change(s=>{s.settings.theme=b.dataset.mode;});
 if(a==='backup-now'){b.disabled=true;try{const result=await chrome.runtime.sendMessage({type:'locus:backup-now'});if(!result?.ok)throw Error(result?.error||'Backup service did not respond. Reload the extension and try again.');toast(result.pending?'A backup is already downloading.':'Backup download started.');}catch(e){toast('Backup failed: '+e.message);}finally{if(b.isConnected)b.disabled=false;}return;}
 if(a==='new-project')entityForm('project');if(a==='open-project')nav('project',id);if(a==='edit-project')entityForm('project',M.locate(state,selected));if(a==='close-modal')closeModal();if(a==='open-task')openTask(id);if(a==='edit-task')entityForm('task',M.locate(state,selected,id));
 if(a==='timer'){await change(s=>{if(s.timer?.projectId===pid&&s.timer?.taskId===tid)M.stopTimer(s);else M.startTimer(s,pid,tid);});refreshTask();}
 if(a==='stop-timer'){await change(s=>M.stopTimer(s));refreshTask();}
 if(a==='unset-progress'){await change(s=>M.setProgress(M.locate(s,pid,tid),null));refreshTask();}
 if(a==='toggle-task'){await change(s=>{const t=M.locate(s,selected,id);M.toggleTask(t,!t.completed);});openTask(id);}
 if(a==='log-time'||a==='edit-time')logTime(pid,tid,a==='edit-time'?id:null);
 if(a==='delete-project')confirmModal('Delete this project?','Its tasks, notes and time entries will also be removed. You can undo this from Backup & restore.',async()=>{if(await change(s=>{if(s.timer?.projectId===selected)M.stopTimer(s);s.projects=s.projects.filter(p=>p.id!==selected);},{backup:true})){closeModal();nav('projects');}});
 if(a==='delete-task')confirmModal('Delete this task?','Its notes and recorded time will also be removed. You can undo this from Backup & restore.',async()=>{if(await change(s=>{if(s.timer?.taskId===id)M.stopTimer(s);const p=M.locate(s,selected);p.tasks=p.tasks.filter(t=>t.id!==id);},{backup:true}))closeModal();});
 if(a==='move'){if(b.dataset.kind==='project'&&state.settings.sort!=='manual')return;await change(s=>{const items=b.dataset.kind==='project'?s.projects:M.locate(s,selected).tasks;const i=items.findIndex(x=>x.id===id),j=i+Number(b.dataset.dir);if(j>=0&&j<items.length)[items[i],items[j]]=[items[j],items[i]];});}
 if(a==='edit-note'){const n=M.locate(state,pid,tid).notes.find(n=>n.id===id);showModal(modalHead('Edit note')+`<form id="edit-note-form" data-pid="${esc(pid)}" data-tid="${esc(tid||'')}" data-id="${esc(id)}"><label>Note<textarea name="text" rows="7" required>${esc(n.text)}</textarea></label><div class="form-buttons"><button type="button" data-action="close-modal">Cancel</button><button class="primary" type="submit">Save note</button></div></form>`);}
 if(a==='delete-note')confirmModal('Delete this note?','This note will be removed. A recovery snapshot will be kept.',async()=>{if(await change(s=>{const x=M.locate(s,pid,tid);x.notes=x.notes.filter(n=>n.id!==id);},{backup:true})){closeModal();if(tid)openTask(tid);}});
 if(a==='print')window.print();if(a==='export'){state=await read();download();toast('JSON backup downloaded.');}if(a==='import')$('#import-file').click();
 if(a==='offload'){state=await read();download();confirmModal('Clear this workspace?','Your JSON download has started. Confirm that the file was saved before clearing. A recovery snapshot will also be kept.',async()=>{if(await change(s=>{s.projects=[];s.timer=null;},{backup:true})){closeModal();toast('Workspace cleared. Recovery snapshot saved.');}});}
 if(a==='recover')confirmModal('Restore previous workspace?','This replaces the current workspace with the last recovery snapshot. The current workspace becomes the new recovery snapshot.',async()=>{try{state=await restoreRecovery();closeModal();render();toast('Workspace restored.');}catch(e){toast(e.message);closeModal();}});
 if(a==='changelog')showModal(modalHead('What’s new')+'<h3>Locus 1.1.0</h3><p>Three design themes, independent dark/light modes, scheduled JSON backups, a user guide and an interactive quick tour.</p><h3>Locus 1.0.0</h3><p>Projects, draggable checklists, progress controls, dated notes, persistent focus timers, manual time entries, visual reports, JSON backup and restore, recovery snapshots, light and dark themes.</p><p class="small-text">Local storage only. No accounts. No tracking.</p>');
});
$('#theme-toggle').onclick=()=>change(s=>{s.settings.theme=s.settings.theme==='dark'?'light':'dark';});
document.addEventListener('input',ev=>{const e=ev.target;if(e.id==='search'){query=e.value;$('#project-results').innerHTML=projectResults();}
 if(e.matches('[data-progress]')){const panel=e.closest('.panel');$('.progress-big',panel).textContent=e.value+'%';}
 if(e.name==='progress'&&e.closest('#entity-form')){const f=e.form;f.elements.unset.checked=false;$('output',f).textContent=e.value+'%';}
 if(e.name==='text'&&e.closest('.note-form')){const f=e.form;drafts.set('note:'+(f.dataset.tid||f.dataset.pid),e.value);}
 if(e.name==='name'&&e.closest('#add-task'))drafts.set('task:'+selected,e.value);
});
document.addEventListener('change',async ev=>{const e=ev.target;if(e.id==='backup-frequency')await change(s=>{s.settings.backupFrequency=e.value;});if(e.id==='sort')await change(s=>{s.settings.sort=e.value;});if(e.id==='show-completed'){showCompleted=e.checked;render();}if(e.id==='report-range'){reportRange=e.value;render();}
 if(e.matches('[data-progress]')){await change(s=>M.setProgress(M.locate(s,e.dataset.progress,e.dataset.task),Number(e.value)));refreshTask();}
 if(e.matches('[data-check]'))await change(s=>M.toggleTask(M.locate(s,selected,e.dataset.check),e.checked));
 if(e.name==='unset'&&e.closest('#entity-form'))$('output',e.form).textContent=e.checked?'—':e.form.elements.progress.value+'%';
});
document.addEventListener('submit',async ev=>{ev.preventDefault();const f=ev.target, fd=new FormData(f),name=String(fd.get('name')||'').trim();
 if(f.id==='entity-form'){const start=fd.get('start'),end=fd.get('end');if(!name){$('#form-error').textContent='Please enter a name.';return;}if(start&&end&&start>end){$('#form-error').textContent='End date must be on or after the start date.';return;}const kind=f.dataset.kind,id=f.dataset.id,revision=modalContext.revision;let newId=id;
 const ok=await change(s=>{if(id&&s.revision!==revision)throw Error('This workspace changed while editing. Close and reopen this form to use the latest version.');let e=id?M.locate(s,selected,kind==='task'?id:null):kind==='task'?M.task(name):M.project(name);Object.assign(e,{name,description:fd.get('description'),start,end});M.setProgress(e,fd.get('unset')?null:Number(fd.get('progress')));if(kind==='project')e.color=fd.get('color');if(!id){newId=e.id;if(kind==='task')M.locate(s,selected).tasks.push(e);else s.projects.push(e);}});if(ok){closeModal();if(kind==='project')nav('project',newId);else openTask(newId);toast('Saved.');}}
 if(f.id==='add-task'){if(!name)return;const pid=selected;if(await change(s=>M.locate(s,pid).tasks.push(M.task(name)))){drafts.delete('task:'+pid);render();$('#add-task input').focus();}}
 if(f.classList.contains('note-form')||f.id==='edit-note-form'){const text=String(fd.get('text')).trim();if(!text)return;const pid=f.dataset.pid,tid=f.dataset.tid||null,id=f.dataset.id;const ok=await change(s=>{const e=M.locate(s,pid,tid);if(id){const n=e.notes.find(n=>n.id===id);if(!n)throw Error('Note no longer exists.');n.text=text;}else e.notes.push({id:M.uid(),text,at:Date.now()});});if(ok){drafts.delete('note:'+(tid||pid));if(id)closeModal();render();if(tid)openTask(tid);toast('Note saved.');}}
 if(f.id==='time-form'){const pid=f.dataset.pid,tid=f.dataset.tid||null,id=f.dataset.id;const start=new Date(fd.get('start')).getTime(),ms=(Number(fd.get('hours'))*60+Number(fd.get('minutes')))*60000,end=start+Math.round(ms);if(!Number.isFinite(start)||ms<=0||!Number.isSafeInteger(end)||end>Date.now()+60000){$('#form-error').textContent='Enter a positive duration that ends no later than now.';return;}if(await change(s=>{const e=M.locate(s,pid,tid);const entry={id:id||M.uid(),start,end,kind:'manual',note:String(fd.get('note'))};if(id){const i=e.sessions.findIndex(x=>x.id===id);if(i<0)throw Error('Time entry no longer exists.');e.sessions[i]=entry;}else e.sessions.push(entry);})){closeModal();if(tid)openTask(tid);toast('Time entry saved.');}}
});
$('#import-file').addEventListener('change',async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file)return;try{const imported=M.validateBackup(JSON.parse(await file.text()));if(imported.timer)M.stopTimer(imported);const pc=imported.projects.length,tc=imported.projects.flatMap(p=>p.tasks).length,nc=imported.projects.reduce((n,p)=>n+p.notes.length+p.tasks.reduce((a,t)=>a+t.notes.length,0),0);confirmModal('Restore this backup?',`<strong>${pc} projects · ${tc} tasks · ${nc} notes</strong><br><br>This replaces your current ${state.projects.length} projects. Your previous workspace will be saved for recovery. Imported timers are paused.`,async()=>{if(await change(s=>Object.assign(s,imported),{backup:true})){closeModal();nav('projects');toast('Backup restored.');}});}catch(e){toast(e instanceof SyntaxError?'This file is not valid JSON.':e.message);}});
document.addEventListener('dragstart',ev=>{const handle=ev.target.closest('.drag-handle');if(!handle)return;if(handle.dataset.kind==='project'&&state.settings.sort!=='manual'){ev.preventDefault();return;}dragged={id:handle.dataset.id,kind:handle.dataset.kind,pid:selected};ev.dataTransfer.effectAllowed='move';ev.dataTransfer.setData('text/plain',dragged.id);handle.closest('[data-drop]').classList.add('dragging');});
document.addEventListener('dragover',ev=>{const target=ev.target.closest('[data-drop]');if(target&&dragged&&target.dataset.drop===dragged.kind){ev.preventDefault();ev.dataTransfer.dropEffect='move';$$('.drop-target').forEach(x=>x.classList.remove('drop-target'));target.classList.add('drop-target');}});
document.addEventListener('drop',async ev=>{const target=ev.target.closest('[data-drop]');if(!target||!dragged||target.dataset.drop!==dragged.kind)return;ev.preventDefault();const d=dragged,rect=target.getBoundingClientRect(),after=ev.clientY>rect.top+rect.height/2;dragged=null;await change(s=>M.move(d.kind==='project'?s.projects:M.locate(s,d.pid).tasks,d.id,target.dataset.id,after));});
document.addEventListener('dragend',()=>{dragged=null;$$('.dragging,.drop-target').forEach(x=>x.classList.remove('dragging','drop-target'));});
window.addEventListener('hashchange',()=>{parseHash();render();});
modal.addEventListener('click',ev=>{if(ev.target===modal){const r=modal.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)closeModal();}});
setInterval(renderTimer,1000);
try{state=await read();M.validateBackup(state);backupMeta=(await chrome.storage.local.get(META_KEY))[META_KEY]||{};tour=createTour({navigate:nav,getProjectId:()=>state.projects[0]?.id||null,onDone:()=>change(s=>{s.settings.onboardingDone=true;})});parseHash();render();subscribe(s=>{if(s&&s.revision!==state.revision){state={...s,settings:{...M.fresh().settings,...s.settings}};render();}});chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[META_KEY]){backupMeta=changes[META_KEY].newValue||{};if(route==='backup')render();}});if(!state.settings.onboardingDone)tour.start('projects');}catch(e){main.innerHTML='<div class="empty"><h2>Locus could not load your workspace.</h2><p id="load-error"></p></div>';$('#load-error').textContent=e.message;}
