export const GUIDE_SECTIONS=[
  ['1. Give an idea a home', 'Choose <strong>New project</strong>. Only its name is required. Add a short description, optional start and end dates, a color and progress whenever you are ready. Click the card to open it. Use <strong>Edit project</strong> to change the details.'],
  ['2. Choose your view', 'Use Search to find names or descriptions. Sort A–Z, Z–A, or by start/end date in either direction; projects without dates come last. Choose <strong>Custom order</strong> and drag the ⋮⋮ handle to arrange projects. Arrow buttons offer the same control without dragging. Your custom order is remembered.'],
  ['3. Turn projects into small steps', 'Open a project and add tasks in the Checklist. Check a task to complete it; uncheck to restore its earlier progress. <strong>Show completed</strong> hides or reveals checked tasks. Drag the handles or use arrow buttons to change task order. Click a task to edit its description, dates, progress, time entries and notes.'],
  ['4. Record progress and updates', 'Drag a progress slider from 0–100%. A dash means unset; <strong>Clear progress</strong> restores it. Overall project progress is independent of its task checklist. Add dated notes for decisions, milestones and next steps. Project and task notes can be edited or deleted, with no app-imposed note count limit.'],
  ['5. Track the work, not just the dates', 'Start a timer on a project or task. Starting another stops the previous timer, so only one runs at a time. Timers continue until stopped, including while Chrome is closed or your computer is asleep. For past work, choose <strong>Log time</strong> and enter the start and duration. Edit an entry to fix a forgotten timer. Manual overlaps are counted as entered.'],
  ['6. Read the bigger picture', '<strong>Reports</strong> shows project progress, time distribution, daily activity and task-level detail. Project time includes direct time and its tasks, each counted once. The time-range filter applies to recorded effort; progress and checklist totals show their current state. Average progress excludes unset projects. Choose <strong>Print / Save PDF</strong> to keep a report.'],
  ['7. Make Locus feel like you', '<strong>Appearance</strong> offers Modern (rounded, violet), Classic (warm paper and serif headings), and Minimalist (quiet grayscale). Light and Dark are separate choices, so every design works in both modes. The sidebar mode button is a shortcut. Preferences stay saved after restarting Chrome and travel in JSON backups.'],
  ['8. Keep automatic backups', '<strong>Backup & restore</strong> lets you choose hourly, daily, weekly or off. Daily is the default. The first scheduled backup is one full interval after setup. Use <strong>Back up now</strong> to test immediately. Files go under <strong>Downloads/Locus/Backups/YYYY-MM</strong>. Each filename includes Manual/Auto, a UTC timestamp, project count and revision. Existing backups are never overwritten or automatically deleted.'],
  ['9. Know when a backup is safe', 'The backup panel shows the next scheduled run, a download in progress, the last successful backup and any error. Success means Chrome reported the file download complete. Schedules need Chrome running; missed runs catch up once when it resumes. Sleep can delay alarms. Chrome download settings may still ask where to save. If a download fails, correct the problem and choose <strong>Back up now</strong>; scheduled backups try again at the next interval.'],
  ['10. Restore or offload your workspace', '<strong>Export JSON</strong> saves every project, task, note, date, time entry and progress update. Exported timers are paused at export time; the original keeps running. <strong>Choose JSON file</strong> validates a backup, shows a summary and asks before replacing the workspace. Imports replace rather than merge. Older Locus 1.0 backups are supported. Backup frequency and appearance are restored too.'],
  ['11. Use recovery and move safely', '<strong>Export & clear workspace</strong> asks you to confirm that the download was saved before clearing. <strong>Restore recovery snapshot</strong> undoes the last import, clear or deletion by swapping workspaces. Only one recovery snapshot is retained. Always export before uninstalling or deleting a Chrome profile. JSON files are unencrypted; keep them somewhere appropriate.'],
  ['12. Update without losing your projects', 'For an unpacked installation, replace the extension files in the <strong>same installed folder</strong>, then click Reload at <strong>chrome://extensions</strong>. Do not remove and reinstall the extension. Locus may ask Chrome to enable its new downloads and alarms permissions. Export a backup before upgrading. All project data stays in the current Chrome profile.']
];
export function guideContent() {return GUIDE_SECTIONS.map(([title,body])=>`<section class="panel"><h2>${title}</h2><p>${body}</p></section>`).join('');}
const STEPS=[
  {title:'Welcome to your own pace.',body:'Locus keeps projects, tasks and notes in this browser. This quick tour shows the essentials. The practice controls never change your real projects.',route:'projects',target:'.brand',example:'A name is enough to begin. Everything else can come later.'},
  {title:'Start small. Stay flexible.',body:'Use New project to create an idea. Open its card to add dates, progress, notes and tasks. Use Custom order to drag cards by their handles.',route:'projects',target:'[data-action="new-project"]',example:'Try a personal project: <strong>Make a reading corner</strong><br>Short description: A quiet spot for the weekend.'},
  {title:'Small steps add up.',body:'Inside a project, add tasks to the checklist. Check to complete, uncheck to bring them back. Click a task for its details and notes. Try this practice checkbox:',route:'project',target:'.task-list',example:'<label class="completion-switch"><input id="tour-practice-check" type="checkbox"> Choose a comfortable chair</label><div id="tour-check-result" class="small-text muted">Task is open</div>'},
  {title:'Progress is yours to set.',body:'Slide to reflect your progress. Project progress is separate from task completion. Use Notes & updates to record decisions and small wins. Try this practice slider:',route:'project',target:'[data-progress]',example:'<label>Practice progress <input id="tour-practice-progress" type="range" min="0" max="100" value="35"></label><strong id="tour-progress-result">35%</strong>'},
  {title:'See where your effort goes.',body:'Start and stop a project or task timer, or log past work manually. Reports combine the entries into one clear picture. A timer keeps running until you stop it, even with Chrome closed.',route:'reports',target:'.reports-grid',example:'<strong>2h project time + 1h task time = 3h total.</strong><br>Tasks are included once in their project’s time.'},
  {title:'Make it feel like home.',body:'Choose Modern, Classic or Minimalist. Then choose Light or Dark independently. These settings are saved, and the sidebar mode button offers a quick toggle.',route:'appearance',target:'.theme-options',example:'<strong>Three designs. Two modes. Six combinations.</strong>'},
  {title:'Keep a copy. Keep moving.',body:'Daily JSON backups are enabled by default. Change the schedule or choose Back up now. The panel confirms when a download succeeds. You can reopen this tour anytime from User guide & tour.',route:'backup',target:'#automatic-backup-panel',example:'<strong>Downloads / Locus / Backups / YYYY-MM</strong><br>Files are timestamped in UTC and never overwrite an earlier backup.'}
];
export function createTour({navigate,getProjectId,onDone}) {
  const dialog=document.querySelector('#tour-dialog');let index=0,active=false,returnRoute='projects';
  const clear=()=>document.querySelectorAll('.tour-highlight').forEach(e=>e.classList.remove('tour-highlight'));
  function highlight(){clear();if(!active)return;const el=document.querySelector(STEPS[index].target);if(el)el.classList.add('tour-highlight');}
  function show() {
    const step=STEPS[index],pid=getProjectId();
    navigate(step.route==='project'&&!pid?'projects':step.route,step.route==='project'?pid:null);
    dialog.innerHTML=`<div class="tour-step">LOCUS QUICK TOUR · ${index+1} OF ${STEPS.length}</div><div class="tour-dots" aria-hidden="true">${STEPS.map((_,i)=>`<span class="${i===index?'current':''}"></span>`).join('')}</div><h2>${step.title}</h2><p>${step.body}</p><div class="tour-example">${step.example}</div><div class="tour-buttons"><button class="skip" data-tour="skip">Skip tour</button><button data-tour="back" ${index===0?'disabled':''}>Back</button><button class="primary" data-tour="next">${index===STEPS.length-1?'Finish':'Next →'}</button></div>`;
    if(!dialog.open)dialog.showModal();highlight();dialog.querySelector('[data-tour="next"]').focus();
  }
  async function finish(){active=false;clear();dialog.close();await onDone();navigate(returnRoute);}
  dialog.addEventListener('click',event=>{const action=event.target.closest('[data-tour]')?.dataset.tour;if(action==='skip')finish();if(action==='back'&&index>0){index--;show();}if(action==='next'){if(index===STEPS.length-1)finish();else{index++;show();}}});
  dialog.addEventListener('change',event=>{if(event.target.id==='tour-practice-check')dialog.querySelector('#tour-check-result').textContent=event.target.checked?'Completed! Uncheck to bring it back.':'Task is open';});
  dialog.addEventListener('input',event=>{if(event.target.id==='tour-practice-progress')dialog.querySelector('#tour-progress-result').textContent=event.target.value+'%';});
  dialog.addEventListener('cancel',event=>{event.preventDefault();finish();});
  return {start(origin='projects'){returnRoute=origin;index=0;active=true;show();},highlight};
}
