import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,project,task,startTimer,validateBackup} from '../model.js';
import {backupFilename,backupPath,createBackupController,BACKUP_ALARM,META_KEY} from '../backup.js';
function harness(){
  let now=Date.parse('2026-09-15T10:00:00.123Z');const s=fresh();s.projects=[project('Room')];s.projects[0].tasks=[task('Paint')];
  const db={locusData:s},downloads=[],items=new Map(),alarms=new Map();let fail=false;
  const api={storage:{local:{async get(key){return {[key]:structuredClone(db[key])};},async set(v){Object.assign(db,structuredClone(v));}}},alarms:{async create(name,data){alarms.set(name,data);},async clear(name){alarms.delete(name);}},downloads:{async download(options){if(fail)throw Error('Download denied');const id=downloads.length+1;downloads.push(options);items.set(id,{id,state:'in_progress'});return id;},async search({id}){return items.has(id)?[items.get(id)]:[];}}};
  const clock=()=>now;return {api,clock,db,downloads,items,alarms,controller:createBackupController(api,clock),advance:ms=>now+=ms,fail:()=>fail=true};
}
test('filenames use UTC, kind, project count and revision in month folders',()=>{const s=fresh();s.projects=[project('A')];s.revision=7;const now=Date.parse('2026-09-15T10:00:00.123Z');assert.equal(backupFilename(s,'auto',now),'Locus_Auto_2026-09-15_10-00-00-123Z_1-projects_r7.json');assert.equal(backupPath(s,'manual',now),'Locus/Backups/2026-09/Locus_Manual_2026-09-15_10-00-00-123Z_1-projects_r7.json');});
test('new installation schedules daily without immediately dumping a file',async()=>{const h=harness();await h.controller.reconcile();assert.equal(h.db[META_KEY].nextAt,h.clock()+86400000);assert.equal(h.alarms.get(BACKUP_ALARM).periodInMinutes,1440);assert.equal(h.downloads.length,0);});
test('a due automatic backup contains a paused valid snapshot of the whole workspace',async()=>{const h=harness();startTimer(h.db.locusData,h.db.locusData.projects[0].id,null,h.clock());await h.controller.reconcile();h.advance(86400000);await h.controller.reconcile();assert.equal(h.downloads.length,1);const options=h.downloads[0];assert.equal(options.saveAs,false);assert.equal(options.conflictAction,'uniquify');const raw=JSON.parse(decodeURIComponent(options.url.split(',')[1]));const s=validateBackup(raw);assert.equal(s.timer,null);assert.equal(s.projects[0].sessions[0].end-s.projects[0].sessions[0].start,86400000);assert.ok(h.db.locusData.timer);assert.equal(h.db.locusData.projects[0].sessions.length,0);assert.equal(s.projects[0].tasks.length,1);});
test('download is successful only after Chrome marks it complete',async()=>{const h=harness();await h.controller.runNow();assert.ok(h.db[META_KEY].pending);assert.equal(h.db[META_KEY].lastSuccess,undefined);h.items.get(1).state='complete';await h.controller.changed(1);assert.equal(h.db[META_KEY].pending,null);assert.equal(h.db[META_KEY].lastSuccess.downloadId,1);});
test('missed runs catch up once and future schedule survives worker restarts',async()=>{const h=harness();await h.controller.reconcile();h.advance(86400000*5);const restarted=createBackupController(h.api,h.clock);await restarted.reconcile();assert.equal(h.downloads.length,1);const next=h.db[META_KEY].nextAt;await restarted.reconcile();assert.equal(h.downloads.length,1);assert.equal(h.db[META_KEY].nextAt,next);});
test('frequency changes reschedule, off removes alarm, manual backup still works',async()=>{const h=harness();await h.controller.reconcile();h.db.locusData.settings.backupFrequency='hourly';await h.controller.reconcile();assert.equal(h.db[META_KEY].nextAt,h.clock()+3600000);h.db.locusData.settings.backupFrequency='off';await h.controller.reconcile();assert.equal(h.alarms.size,0);assert.equal(h.db[META_KEY].nextAt,null);await h.controller.runNow();assert.equal(h.downloads.length,1);});
test('concurrent requests share an in-progress download',async()=>{const h=harness();await Promise.all([h.controller.runNow(),h.controller.runNow()]);assert.equal(h.downloads.length,1);});
test('interrupted backup preserves last success and displays failure',async()=>{const h=harness();await h.controller.runNow();h.items.get(1).state='complete';await h.controller.changed(1);await h.controller.runNow();h.items.set(2,{id:2,state:'interrupted',error:'FILE_NO_SPACE'});await h.controller.changed(2);assert.equal(h.db[META_KEY].lastSuccess.downloadId,1);assert.equal(h.db[META_KEY].error,'FILE_NO_SPACE');assert.equal(h.db[META_KEY].pending,null);});
test('download rejection records an error without claiming success',async()=>{const h=harness();h.fail();await assert.rejects(h.controller.runNow(),/Download denied/);assert.equal(h.db[META_KEY].error,'Download denied');assert.equal(h.db[META_KEY].lastSuccess,undefined);});
test('worker restart reconciles a download completed while suspended',async()=>{const h=harness();await h.controller.runNow();h.items.get(1).state='complete';await createBackupController(h.api,h.clock).reconcile();assert.equal(h.db[META_KEY].lastSuccess.downloadId,1);assert.equal(h.db[META_KEY].pending,null);});
test('a file completed before its download ID is stored is detected by search',async()=>{const h=harness();const original=h.api.downloads.download;h.api.downloads.download=async opts=>{const id=await original(opts);h.items.get(id).state='complete';return id;};await h.controller.runNow();assert.equal(h.db[META_KEY].lastSuccess.downloadId,1);});
test('legacy 1.0 backups keep light/dark preference and receive new defaults',()=>{const s=fresh();s.settings={sort:'end:desc',theme:'dark'};const restored=validateBackup(s);assert.deepEqual(restored.settings,{sort:'end:desc',theme:'dark',design:'modern',backupFrequency:'daily',onboardingDone:false});});
test('all six appearance combinations and schedule/onboarding choices survive backup restore',()=>{for(const design of ['modern','classic','minimalist'])for(const theme of ['light','dark']){const s=fresh();Object.assign(s.settings,{design,theme,backupFrequency:'weekly',onboardingDone:true});assert.deepEqual(validateBackup(s).settings,s.settings);}});
